### ISSUE TITLE
Implement skew for dataset augmentation

### ISSUE THREAD

**Issue by Chintan2108** [Chintan2108/Cloud-Removal-in-Satellite-Images-using-Conditional-Generative-Adversarial-Networks#4]
* Currently the training dataset is augmented from a single pair of cloudy and cloud-free images
* The augmentation is performed only by rotation of 0, 90, 180 and -90 degrees which gives us 4 pairs, say 1,2,3 and 4
* These four pairs are then stacked iteratively 10 times as: ```[1,2,3,4,1,2,3,4,1,2]```

- [ ] Implement skew operations on the cloudy and cloud-free images, and then perform the rotation operations. You will now have 4 pairs of original *(unskewed)* images, say, [1, 2, 3, 4] and 4 pairs of the skewed images, say [1', 2', 3', 4']

- [ ] Prepare two new training datasets by stacking 10 times as ```[1,2,3,4,1',2',3',4',1,1']```

**Comment by Preetesh21** [comment]
Hey, @Chintan2108  you would want a Jupyter Notebook for the Data Augmentation on the images or a Python file.

**Comment by Chintan2108** [comment]
> Hey, @Chintan2108 you would want a Jupyter Notebook for the Data Augmentation on the images or a Python file.

Hi @Preetesh21 Ideally it would be great if you could add this logic in the sections 3.3 and 3.4 of the current notebook. 
Even if you do it in a separate file, it's okay. Make sure you write your code with proper docstrings and comments. Just make sure you upload the new dataset in the drive folder with appropriate naming convention.
